services:
  db:
    container_name: mysql_database
    image: mysql:oracle
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - path: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${USER_DB_PASSWORD}
    restart: always
  
  phpMyAdmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    ports:
      - "8080:80"
    env_file:
      - path: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${USER_DB_PASSWORD}
      - PMA_HOST=db
    restart: always
